inherits_from:
    - .haml-lint_todo.yml

exclude:
  - lib/templates/haml/scaffold/*

linters:
  InlineStyles:
    enabled: false

  InstanceVariables:
    enabled: false

  LineLength:
    enabled: false
    max: 80

  ConsecutiveComments:
    enabled: false

  RuboCop:
    enabled: true
    ignored_cops:
      # These cops are incredibly noisy when it comes to HAML templates, so we
      # ignore them.
      - Layout/BlockAlignment
      - Layout/EndAlignment
      - Layout/EmptyLineAfterGuardClause
      - Layout/LineLength
      - Lint/Void
      - Lint/InterpolationCheck
      - Naming/FileName
      - Style/AlignParameters
      - Style/BlockNesting
      - Style/ElseAlignment
      - Style/FileName
      - Style/FinalNewline
      - Style/FrozenStringLiteralComment
      - Style/IfUnlessModifier
      - Style/IndentationWidth
      - Style/Next
      - Style/TrailingWhitespace
      - Style/WhileUntilModifier
      - Cop/StaticTranslationDefinition

      # Too many offenses to enable this for now.
      - Style/For
      - Layout/TrailingEmptyLines
      - Layout/SpaceInsideHashLiteralBraces
      - Layout/SpaceAfterComma
      - Style/HashSyntax
      - Style/QuotedSymbols
      - Layout/SpaceInsideStringInterpolation
      - Layout/SpaceInsideArrayLiteralBrackets
      - Layout/SpaceAfterColon
      - Layout/SpaceBeforeComma
      - Style/SymbolArray
      - Lint/AmbiguousOperatorPrecedence
      - Layout/LeadingCommentSpace
      - Style/SymbolProc
      - Style/WordArray
      - Style/EachWithObject
      - Style/MapToHash
      - Style/ParallelAssignment
      - Style/MethodCallWithoutArgsParentheses
      - Security/Eval
      - Lint/SymbolConversion
      - Style/PercentLiteralDelimiters
      - Style/RedundantInterpolation
      - Style/RandomWithOffset
      - Style/CaseEquality
      - Style/MultilineBlockChain
      - Layout/MultilineMethodCallBraceLayout
      - Style/RedundantConditional
      - Style/IfWithBooleanLiteralBranches
      - Lint/RedundantSplatExpansion
      - Style/UnlessElse
      - Style/ZeroLengthPredicate
      - Layout/TrailingWhitespace
      - Style/CommentAnnotation
      - Style/NumericLiteralPrefix
      - Style/StringLiteralsInInterpolation
      - Lint/BooleanSymbol
      - Style/NestedParenthesizedCalls
      - Style/SignalException
      - Layout/ElseAlignment
      - Layout/IndentationWidth
      - Style/IfInsideElse
      - Style/RedundantCondition
      - Style/SelfAssignment
      - Layout/EmptyLines
      - Style/SymbolLiteral
      - Style/RegexpLiteral
      - Style/PreferredHashMethods
      - Style/NilComparison
      - Style/CommentedKeyword
      - Layout/EmptyComment
      - Style/RedundantStringEscape
