default: &default
  adapter: postgis
  encoding: unicode
  pool: 5
  postgis_extension: []
  schema_search_path: public,postgis,lexicon
  username: <%= ENV.fetch("DB_USERNAME","ekylibre") %>
  password: <%= ENV.fetch("DB_PASSWORD","ekylibre") %>
  host: <%= ENV.fetch("DB_HOST","") %>
  port: <%= ENV.fetch("DB_PORT","5432") %>


development:
  <<: *default
  database: <%= ENV.fetch("DB_DEV_NAME","eky_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_TEST_NAME","eky_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_PROD_NAME","eky_production") %>